# ??????????????????????????????????????????
# Database ? SQL Server
# ??????????????????????????????????????????
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=GlassStore;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# ??????????????????????????????????????????
# JWT
# ??????????????????????????????????????????
jwt.secret=GlassDB_SuperSecretKey_2024_Group5_ABCDEF
jwt.expiration-ms=86400000
spring.security.debug=true
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB